### ISSUE TITLE
I don't really understand how to use this?

### ISSUE THREAD

**Issue by Tzikas** [Astrocoders/meteor-one-signal#3]
Could you provide a `hello world` example?  I simply added 
```
 const data = {
    contents: {
      en: 'Hey! Wazup? We miss you.',  
    },
  };

  OneSignal.Notifications.create([playersId], data);
```

to my server side main.js, and added a settings.json file with the OneSignal App ID, and Rest API key.

**Comment by guilhermedecampo** [comment]
Hey @Tzikas thank you for issue.

You should call the `OneSignal.Notifications.create` method when there is an action you would like to notify your users that are in an array in this example `playersId`. 

We are using React Native so we generate the playersId via the npm package `react-native-onesignal`

```
import Meteor from 'react-native-meteor';
import OneSignal from 'react-native-onesignal';

export default function SetupOneSignal(){
  OneSignal.idsAvailable(credentials => {
    console.log('[OneSignal] Sending crendetials to server');
    Meteor.call('oneSignal/saveCredentials', credentials);
  });
};
```

and saving it on the user collection via `Meteor.call('oneSignal/saveCredentials', credentials);`

a PR with an React Native example is welcome.

**Comment by Tzikas** [comment]
Thanks for the reply, but I'm not very good, and I still don't understand how to make use of this package.  A simple `hello world` example that i could clone or copy and paste and run with `meteor run ios-device` would be greatly appreciated.  Either way thanks again for replying.

**Comment by AndyNormore** [comment]
Don't know why this is close, this package is totally useless with out a guide as to how this works. I get:

Uncaught TypeError: Cannot read property 'create' of undefined

**Comment by guilhermedecampo** [comment]
Hi @AndyNormore,

You should be more clear on what you have done to receive this error.

This package is being used in production apps. 
We don't have time to write a full guide but we are glad to help if you want to.

A really good start to understand what is happening is just scan through the code.

Best,

**Comment by AndyNormore** [comment]
Thanks for the reply, 

I have simply followed the instructions to configure. I get no problems to install.

When I attempt to call **OneSignal.Notifications.create([playersId], data);** from within Meteor, I get the error of:

**Uncaught TypeError: Cannot read property 'create' of undefined**

So it seems that the package isn't installed properly? 

Can you please explain if I can set the PlayersID data to.. my Meteor user ID? An email? We don't understand how that is set.
